### ISSUE TITLE
Free product tab not working

### ISSUE THREAD

**Issue by BlazeNeon** [RenewedPlains/WooCommerce-Product-Coupon#2]
![image](https://user-images.githubusercontent.com/37164108/53396279-07088580-39df-11e9-9a63-29d8f72e5a54.png)

Can you tell me how to solve this problem?
@RenewedPlains

**Comment by RenewedPlains** [comment]
Hey sorry for the delay, I will update this plugin in the next few days. ;) it's an older one. 

Thanks for the download! :D

**Comment by RenewedPlains** [comment]
Please excuse the long wait. I was able to fix the error. The order from content panels was wrong. Many thanks for the download :)
